// <auto-generated />
using System;
using Legaria.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Legaria.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LegariaDbContext))]
    [Migration("20260804180042_OrganizationProvisioningAndDivipola")]
    partial class OrganizationProvisioningAndDivipola
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Legaria.Domain.Authentication.AccountEmail", b =>
                {
                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("PlatformUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_user_id");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("NormalizedEmail")
                        .HasName("pk_account_emails");

                    b.HasIndex("PlatformUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_account_emails_platform_user_id");

                    b.HasIndex("UserAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_account_emails_user_account_id");

                    b.ToTable("account_emails", null, t =>
                        {
                            t.HasCheckConstraint("ck_account_emails_account_type", "(account_type = 'PLATFORM' AND platform_user_id IS NOT NULL AND user_account_id IS NULL) OR (account_type = 'TENANT' AND user_account_id IS NOT NULL AND platform_user_id IS NULL)");

                            t.HasCheckConstraint("ck_account_emails_single_account", "num_nonnulls(platform_user_id, user_account_id) = 1");
                        });
                });

            modelBuilder.Entity("Legaria.Domain.Authentication.AccountToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<DateTimeOffset?>("DeliveryFailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_failed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("PlatformUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_user_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id")
                        .HasName("pk_account_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_account_tokens_token_hash");

                    b.HasIndex("PlatformUserId", "Purpose", "ExpiresAt")
                        .HasDatabaseName("ix_account_tokens_platform_user_id_purpose_expires_at");

                    b.HasIndex("UserAccountId", "Purpose", "ExpiresAt")
                        .HasDatabaseName("ix_account_tokens_user_account_id_purpose_expires_at");

                    b.ToTable("account_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_account_tokens_account_type", "(account_type = 'PLATFORM' AND platform_user_id IS NOT NULL AND user_account_id IS NULL) OR (account_type = 'TENANT' AND user_account_id IS NOT NULL AND platform_user_id IS NULL)");

                            t.HasCheckConstraint("ck_account_tokens_single_account", "num_nonnulls(platform_user_id, user_account_id) = 1");
                        });
                });

            modelBuilder.Entity("Legaria.Domain.Authentication.PlatformUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset?>("LockoutEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end_at");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_platform_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_platform_users_normalized_email");

                    b.HasIndex("Role")
                        .IsUnique()
                        .HasDatabaseName("ix_platform_users_role")
                        .HasFilter("\"role\" = 'OWNER'");

                    b.ToTable("platform_users", null, t =>
                        {
                            t.HasCheckConstraint("ck_platform_users_role", "role IN ('OWNER', 'PLATFORM_ADMIN')");

                            t.HasCheckConstraint("ck_platform_users_status", "status IN ('ACTIVE', 'SUSPENDED')");
                        });
                });

            modelBuilder.Entity("Legaria.Domain.Authentication.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("PlatformUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_user_id");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_refresh_sessions");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_sessions_family_id");

                    b.HasIndex("ReplacedBySessionId")
                        .HasDatabaseName("ix_refresh_sessions_replaced_by_session_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_sessions_token_hash");

                    b.HasIndex("PlatformUserId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_sessions_platform_user_id_expires_at");

                    b.HasIndex("UserAccountId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_sessions_user_account_id_expires_at");

                    b.ToTable("refresh_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_sessions_single_account", "num_nonnulls(platform_user_id, user_account_id) = 1");
                        });
                });

            modelBuilder.Entity("Legaria.Domain.Authentication.SecurityAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .HasColumnType("text")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("outcome");

                    b.Property<Guid?>("PlatformUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_user_id");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_security_audit_events");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_security_audit_events_created_at");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_security_audit_events_organization_id");

                    b.HasIndex("PlatformUserId")
                        .HasDatabaseName("ix_security_audit_events_platform_user_id");

                    b.HasIndex("UserAccountId")
                        .HasDatabaseName("ix_security_audit_events_user_account_id");

                    b.ToTable("security_audit_events", (string)null);
                });

            modelBuilder.Entity("Legaria.Domain.Authentication.SystemRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_system_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_system_roles_code");

                    b.ToTable("system_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4ee7a2e-c508-4c67-9132-877d600d74d2"),
                            Code = "SUPER_ADMIN",
                            Name = "Superadministrador"
                        },
                        new
                        {
                            Id = new Guid("ca3759ba-98b6-4de0-b3a7-44ef0f274e87"),
                            Code = "BRANCH_ADMIN",
                            Name = "Administrador de sucursal"
                        });
                });

            modelBuilder.Entity("Legaria.Domain.Authentication.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsInitialAdministrator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_initial_administrator");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset?>("LockoutEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end_at");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user_accounts");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_user_accounts_normalized_email");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_accounts_organization_id")
                        .HasFilter("\"is_initial_administrator\" = TRUE");

                    b.HasIndex("OrganizationId", "EmployeeId")
                        .HasDatabaseName("ix_user_accounts_organization_id_employee_id");

                    b.HasIndex("OrganizationId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ix_user_accounts_organization_id_id");

                    b.ToTable("user_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_accounts_status", "status IN ('ACTIVE', 'SUSPENDED')");
                        });
                });

            modelBuilder.Entity("Legaria.Domain.Authentication.UserRole", b =>
                {
                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.Property<Guid>("SystemRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_role_id");

                    b.HasKey("UserAccountId", "SystemRoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("SystemRoleId")
                        .HasDatabaseName("ix_user_roles_system_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Legaria.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_number");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_employees_organization_id_id");

                    b.HasIndex("OrganizationId", "DocumentType", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_organization_id_document_type_document_number");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Legaria.Domain.Tenancy.Department", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Legaria.Domain.Tenancy.Municipality", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("department_code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Code")
                        .HasName("pk_municipalities");

                    b.HasIndex("DepartmentCode", "Name")
                        .HasDatabaseName("ix_municipalities_department_code_name");

                    b.ToTable("municipalities", (string)null);
                });

            modelBuilder.Entity("Legaria.Domain.Tenancy.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("address");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("MunicipalityCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("municipality_code")
                        .IsFixedLength();

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("nit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trade_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VerificationDigit")
                        .HasColumnType("integer")
                        .HasColumnName("verification_digit");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("MunicipalityCode")
                        .HasDatabaseName("ix_organizations_municipality_code");

                    b.HasIndex("Nit")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_nit");

                    b.ToTable("organizations", null, t =>
                        {
                            t.HasCheckConstraint("ck_organizations_status", "status IN ('ACTIVE', 'SUSPENDED')");
                        });
                });

            modelBuilder.Entity("Legaria.Domain.Authentication.AccountEmail", b =>
                {
                    b.HasOne("Legaria.Domain.Authentication.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("PlatformUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_account_emails_platform_users_platform_user_id");

                    b.HasOne("Legaria.Domain.Authentication.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_account_emails_user_accounts_user_account_id");
                });

            modelBuilder.Entity("Legaria.Domain.Authentication.AccountToken", b =>
                {
                    b.HasOne("Legaria.Domain.Authentication.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("PlatformUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_account_tokens_platform_users_platform_user_id");

                    b.HasOne("Legaria.Domain.Authentication.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_account_tokens_user_accounts_user_account_id");
                });

            modelBuilder.Entity("Legaria.Domain.Authentication.RefreshSession", b =>
                {
                    b.HasOne("Legaria.Domain.Authentication.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("PlatformUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_sessions_platform_users_platform_user_id");

                    b.HasOne("Legaria.Domain.Authentication.RefreshSession", null)
                        .WithMany()
                        .HasForeignKey("ReplacedBySessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_sessions_refresh_sessions_replaced_by_session_id");

                    b.HasOne("Legaria.Domain.Authentication.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_sessions_user_accounts_user_account_id");
                });

            modelBuilder.Entity("Legaria.Domain.Authentication.SecurityAuditEvent", b =>
                {
                    b.HasOne("Legaria.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_security_audit_events_organizations_organization_id");

                    b.HasOne("Legaria.Domain.Authentication.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("PlatformUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_security_audit_events_platform_users_platform_user_id");

                    b.HasOne("Legaria.Domain.Authentication.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_security_audit_events_user_accounts_user_account_id");
                });

            modelBuilder.Entity("Legaria.Domain.Authentication.UserAccount", b =>
                {
                    b.HasOne("Legaria.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_accounts_organizations_organization_id");

                    b.HasOne("Legaria.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_accounts_employees_organization_id_employee_id");
                });

            modelBuilder.Entity("Legaria.Domain.Authentication.UserRole", b =>
                {
                    b.HasOne("Legaria.Domain.Authentication.SystemRole", "SystemRole")
                        .WithMany()
                        .HasForeignKey("SystemRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_system_roles_system_role_id");

                    b.HasOne("Legaria.Domain.Authentication.UserAccount", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_user_accounts_user_account_id");

                    b.Navigation("SystemRole");
                });

            modelBuilder.Entity("Legaria.Domain.Employees.Employee", b =>
                {
                    b.HasOne("Legaria.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_organizations_organization_id");
                });

            modelBuilder.Entity("Legaria.Domain.Tenancy.Municipality", b =>
                {
                    b.HasOne("Legaria.Domain.Tenancy.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_municipalities_departments_department_code");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Legaria.Domain.Tenancy.Organization", b =>
                {
                    b.HasOne("Legaria.Domain.Tenancy.Municipality", null)
                        .WithMany()
                        .HasForeignKey("MunicipalityCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organizations_municipalities_municipality_code");
                });

            modelBuilder.Entity("Legaria.Domain.Authentication.UserAccount", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
