import {
  symRoundedAddBusiness,
  symRoundedAdminPanelSettings,
  symRoundedApartment,
  symRoundedArrowBack,
  symRoundedArrowForward,
  symRoundedBlock,
  symRoundedCheckCircle,
  symRoundedChevronLeft,
  symRoundedChevronRight,
  symRoundedClose,
  symRoundedDescription,
  symRoundedError,
  symRoundedForwardToInbox,
  symRoundedFolder,
  symRoundedGroups,
  symRoundedHelp,
  symRoundedInfo,
  symRoundedKeyboardArrowLeft,
  symRoundedKeyboardArrowRight,
  symRoundedLock,
  symRoundedLogout,
  symRoundedMail,
  symRoundedMenu,
  symRoundedNotifications,
  symRoundedPersonAdd,
  symRoundedPersonSearch,
  symRoundedPhoneInTalk,
  symRoundedRefresh,
  symRoundedSearch,
  symRoundedStorefront,
  symRoundedTaskAlt,
  symRoundedTune,
  symRoundedUploadFile,
  symRoundedVerifiedUser,
  symRoundedVisibility,
  symRoundedVisibilityOff,
  symRoundedWarning,
} from '@quasar/extras/material-symbols-rounded'

export const icons = {
  addBusiness: symRoundedAddBusiness,
  admin: symRoundedAdminPanelSettings,
  apartment: symRoundedApartment,
  arrowBack: symRoundedArrowBack,
  arrowForward: symRoundedArrowForward,
  block: symRoundedBlock,
  check: symRoundedCheckCircle,
  chevronLeft: symRoundedChevronLeft,
  chevronRight: symRoundedChevronRight,
  close: symRoundedClose,
  description: symRoundedDescription,
  error: symRoundedError,
  forwardToInbox: symRoundedForwardToInbox,
  folder: symRoundedFolder,
  groups: symRoundedGroups,
  help: symRoundedHelp,
  info: symRoundedInfo,
  keyboardArrowLeft: symRoundedKeyboardArrowLeft,
  keyboardArrowRight: symRoundedKeyboardArrowRight,
  lock: symRoundedLock,
  logout: symRoundedLogout,
  mail: symRoundedMail,
  menu: symRoundedMenu,
  notifications: symRoundedNotifications,
  personAdd: symRoundedPersonAdd,
  personSearch: symRoundedPersonSearch,
  phone: symRoundedPhoneInTalk,
  refresh: symRoundedRefresh,
  search: symRoundedSearch,
  storefront: symRoundedStorefront,
  taskAlt: symRoundedTaskAlt,
  tune: symRoundedTune,
  upload: symRoundedUploadFile,
  verified: symRoundedVerifiedUser,
  visibility: symRoundedVisibility,
  visibilityOff: symRoundedVisibilityOff,
  warning: symRoundedWarning,
} as const
